### ISSUE TITLE
Extend validation to validate multiple resources with the same schema

### ISSUE THREAD

**Issue by mcweba** [swisspush/gateleen#10]
#### Current validation feature

Let's say you have the following structure of resources and want to validate the **res_1**, **res_2** and **res_3** resource.
![image](https://cloud.githubusercontent.com/assets/8819088/13670408/0b40071a-e6ca-11e5-8ea1-28df4db5940a.png)
To validate these resources, you would have to deploy 3 different schemas and configure them in the validation resource like this:

```json
{
  "resources": [
    {
      "url": "/playground/server/tests/resources/res_1",
      "method": "PUT"
    },
    {
      "url": "/playground/server/tests/resources/res_2",
      "method": "PUT"
    },
    {
      "url": "/playground/server/tests/resources/res_3",
      "method": "PUT"
    }    
  ]
}
```

#### Required additional validation functionality
So when **res_1**, **res_2** and **res_3** are _instances_ of the same resource and therefore can be validated by the same schema, it would be useful to define one schema only.

It would be useful when the configuration could look something like this:
```json
{
  "resources": [
    {
      "url": "/playground/server/tests/resources/.*",
      "method": "PUT"
    }    
  ]
}
```
This would mean that all resources under _/playground/server/tests/resources/_ will be validated. It has to be defined how the corresponding schema for this resources can be selected (maybe by defining the name of the schema as additional property in the validation resource).

**Comment by lbovet** [comment]
Is it not already the case when using the _ placeholder in the schema path?

**Comment by mcweba** [comment]
You're absolutely right, using the underscore (_) in the schema path does the trick. Maybe the documentation is a little bit weak here :wink:
