### ISSUE TITLE
Use Gateleen Playground in cluster mode with other Vert.x instances to share the event bus

### ISSUE THREAD

**Issue by xsSilva** [swisspush/gateleen#133]
I am trying to have the Playground in cluster mode in order to make possible the communication between my backend and the API Gateway, via Event Bus, but I cannot make it work.  I try to start it with `java -jar build/libs/playground.jar -cluster`, what should make it in cluster mode with other verticles but it is not working. It doesn't also work using a cluster configuration file.
I am pretty sure that it is not actually creating the cluster, otherwise, it should receive messages like other instances I have running. I do not find information regarding this in the documentation and I'm getting really confused since no error messages are displayed. 

Has anyone used the Playground example in cluster mode?

**Comment by mcweba** [comment]
Have you tried to setup a clustered vertx via
```java
Vertx.clusteredVertx(VertxOptions options, Handler<AsyncResult<Vertx>> resultHandler)
```
and then use the clustered Vertx from resultHandler to deploy the playground verticle (org.swisspush.gateleen.playground.Server)?

**Comment by xsSilva** [comment]
Thanks for the suggestion. I've done like you suggested but it is still not working...

The problem persists using the default cluster configurations and using a "custom" configurations file. Every message sent from another verticle (that was supposed to be in the cluster) for the clustered event bus is not received by the playground.

I've found 2 problems:

1. When I run the playground and the playground verticle (org.swisspush.gateleen.playground.Server) is setting up a clustered Vert.x (just as you said in the previous comment), it shows the usual Vert.x message regarding cluster members (i.e., `Members [1] {Member [192.168.2.61]:5701 this}`). When I launch another verticle in cluster mode it is not seen in the playground (and the message keeps the same), what makes me think that they are not clustered. If I change the `cluster.xml` file to use TCP/IP, even on the same machine, the problems persists. If I do both of the operations with another "receiver" verticle, other than the playground one, everything works as it should. I can use the same cluster configurations or the default ones with other verticles and the communication in the cluster is possible but the playground verticle is not able to receive the messages.


2. I've used the `vertx-cluster-watchdog` in order to test the cluster. As soon as I launch it, the playground verticle displays the message `Members [2] {Member [192.168.2.61]:5701 this	Member 192.168.2.61]:5703}`. I cannot understand how the watchdog is able to connect to the cluster shown in the playground when no other verticle can... Even when using the `cluster.xml` configurations file, the same problem persists and it seems that the only verticle that the playground clustered verticle sees is the watchdog one. 
I feel like the playground verticle does not stay in a cluster with other verticles or it would detect them and answer the watchdog.

    2.1.  The watchdog always displays `SEVERE: ClusterWatchdog known cluster members: 2 responses: 1`, when the playground is on. 


Can you understand what is happening? Thank you for your help!

**Comment by xsSilva** [comment]
I've also tried to do this:

1. Start a receiver verticle with a `cluster.xml` file

2. Start a sender verticle with the same `cluster.xml` file

3. Launch the `vertx-cluster-watchdog`. It reports that the cluster is consistent.

4. Start the playground with the same `cluster.xml` file as the other 2 verticles.

5. The playground verticle shows a cluster with only 2 members and the `vertx-cluster-watchdog` displays `displays SEVERE: ClusterWatchdog known cluster members: 2 responses: 1`.

It seems that the playground is "ignoring" the cluster.

What do you think of this? Thanks again!

**Comment by mcweba** [comment]
@lbovet do you have an idea what could be the problem with the clustering?

**Comment by lbovet** [comment]
Weird. Did you modify https://github.com/swisspush/gateleen/blob/master/gateleen-playground/src/main/java/org/swisspush/gateleen/playground/Server.java to use ´Vertx.clusteredVertx(VertxOptions options, Handler<AsyncResult<Vertx>> resultHandler)´ instead of the vanilly ´Vertx.vertx()´

**Comment by xsSilva** [comment]
@lbovet 
Yes, I did modify it like you and @mcweba suggested. Even using `Vertx.clusteredVertx(VertxOptions options, Handler<AsyncResult<Vertx>> resultHandler)` the cluster is still not working properly and no messages are received. 
Did it work for you? I have tried to modify the cluster options and, even doing so, I cannot use the Playground in cluster mode. I am not understanding what the problem could be...
Thanks for the help!

**Comment by lbovet** [comment]
AFAIK, the cluster watchdog only checks multiple instances of gateleen. It is not meant to be used with non-gateleen cluster members, I think. Because those are not answering to requests.
Did you manage to setup a working client-server cluster with your client verticle not using gateleen?

**Comment by xsSilva** [comment]
Yes, I have managed to setup multiple client-server clusters without using gateleen. Do you think any gateleen configuration overrides the clustering of Vert.x, somehow?

It should be really straightforward to deploy as `Vertx.clusteredVertx(VertxOptions options, Handler<AsyncResult<Vertx>> resultHandler)` and share the event bus with other clustered verticle. 

Thanks!

**Comment by lbovet** [comment]
So you deploy your own verticle in within the same vertx instance of the playground Server verticle, right? Can you share a branch of your setup to have a look?

**Comment by xsSilva** [comment]
@lbovet and @mcweba 
I've successfully created a cluster using the playground Server and other verticles!

1 . I've created a clustered Vert.x instance using `Vertx.clusteredVertx(VertxOptions options, Handler<AsyncResult<Vertx>> resultHandler)` as you suggested. After that,  with the clustered Vert.x instance, I've deployed my verticles. Those verticles "play" a little with the event bus, just for testing purposes.
2. I've created a cluster configuration file on the gateleen directory.
3. I've compiled the project
4. I've run the jar by typing `java -jar gateleen-playground/build/libs/playground.jar -cp . -cluster`

After that, my verticles could communicate with the playground successfully! 

Thank you very much for the help, @mcweba and @lbovet! You might want to close the issue since the problem is solved.

**Comment by floriankammermann** [comment]
Just a note on the cluster watchdog, its not tied to gateleen, it works independent. 
You can deploy the https://github.com/swisspush/vertx-cluster-watchdog in any vertx instance. 
You can provide the cluster member (nodes) count over the config, or you can let the watchdog figure it out itself, by asking the hazelcast cluster manager.

**Comment by xsSilva** [comment]
@floriankammermann 
Thank you! I did understand that it was not tied to Gateleen, but thank you very much for the note and the clarification on the nodes counter! :)
