### ISSUE TITLE
Add additional monitoring metrics

### ISSUE THREAD

**Issue by mcweba** [swisspush/gateleen#14]
For documentation and monitoring purposes, it would be useful to be able to extract information about the requests and their matching routing rule.

The request could be identfied by a configurable (system property) request header name. To identify the rule, an additional (unique) property called **name** could be added to each routing rule entry.

**Comment by lbovet** [comment]
Is the name attribute now mandatory? This would break compatibility. Is there a way to keep it optional?

**Comment by mcweba** [comment]
I make the attribute optional and log a warning when the feature is activated and a rule without a name matches.
