### ISSUE TITLE
Travis build fails in "trusty" environment

### ISSUE THREAD

**Issue by dominik-cnx** [swisspush/gateleen#159]
Observed after a fork, Travis now uses the Trusty environment by default (replaces "precise") and there are test failures such as the one below. A obvious difference is the Redis version:

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	**trusty**

Redis version
redis-server **3.2.9**

Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	**precise**

Redis version
redis-server **2.8.19**

But there might be other factors as well. Here a link to the doc regarding EOL of **precise**
https://blog.travis-ci.com/2017-04-17-precise-EOL

org.swisspush.gateleen.core.lock.impl.RedisBasedLockTest > testReleaseExpiredLock FAILED
java.lang.AssertionError: Expected true
at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:432)
at io.vertx.ext.unit.impl.TestContextImpl.assertTrue(TestContextImpl.java:282)
at io.vertx.ext.unit.impl.TestContextImpl.assertTrue(TestContextImpl.java:288)
at org.swisspush.gateleen.core.lock.impl.RedisBasedLockTest.lambda$testReleaseExpiredLock$10(RedisBasedLockTest.java:158)
org.swisspush.gateleen.core.lock.impl.RedisBasedLockTest > testAcquireLockAgain STARTED
org.swisspush.gateleen.core.lock.impl.RedisBasedLockTest > testAcquireLockAgain FAILED
java.util.concurrent.TimeoutException
org.swisspush.gateleen.core.lock.impl.RedisBasedLockTest > testReleaseExistingLockWithCorrectToken STARTED
org.swisspush.gateleen.core.lock.impl.RedisBasedLockTest > testReleaseExistingLockWithCorrectToken FAILED
java.util.concurrent.TimeoutException
org.swisspush.gateleen.core.lock.impl.RedisBasedLockTest > testReleaseExistingLockWithWrongToken STARTED
org.swisspush.gateleen.core.lock.impl.RedisBasedLockTest > testReleaseExistingLockWithWrongToken FAILED
java.util.concurrent.TimeoutException

**Comment by mcweba** [comment]
By the way, we have a running instance of our server application running on gateleen **1.1.4** and having a redis-server with version **3.2.10**. We do not have noticed any errors so far.

**Comment by dominik-cnx** [comment]
Yep, had a look on a OS X box with Redis 3.2.11 (00000000/0) 64 bit
-> server works no problem, don't know if the tests pass though
