### ISSUE TITLE
gateleen-hook: Allow flexible RequestQueue configuration per hook

### ISSUE THREAD

**Issue by mcweba** [swisspush/gateleen#178]
The current implementation of the _HookHandler_ allows the definition of exactly one _QueueClient_ implementation.
The _QueueClient_ provides access to the queuing mechanism implemented by [vertx-redisques](https://github.com/swisspush/vertx-redisques).

Since the _HookHandler_ allows a single _QueueClient_ only, all the queueing related actions will be performed against the same _vertx-redisques_ instance.

We have now the requirement to let hooks be performed on different _vertx-redisques_ instances, therefore we should be able to
* configure the _vertx-redisques_ instance to be used in the hook configuration
* provide multiple _QueueClient_ implementations in the _HookHandler_

To configure the _vertx-redisques_ instance to be used in the hook configuration, a property called _queueClient_ could be added. When no _queueClient_ property is defined (or not valid), the default QueueClient is used.

Example hook configuration:
```
PUT http://myserver7012/gateleen/everything/_hooks/listeners/http/myexample
{
    "methods": [
        "PUT"
    ],
    "queueClient"; "someOtherQueueClient",
    "destination": "/gateleen/example/thePosition",
    "filter": "/gateleen/everything/.*/position.*",
    "staticHeaders": {
        "X-Expire-After": "3600"
    }    
}
```

**Comment by lbovet** [comment]
Choosing a different queue implementation is not something specific to
hooks. We should open this possibility to other contexts (normal requests,
schedulers, ...).
Routing to a different queue implementation should be actually done by the
queueClient itself. We can have a dispatchingQueueClient that inspects a
header (or a prefix of the x-queue name) and delegate to a wrapped
queueClient. We have actually done this in our project to use a transient
implementation of queues.
This actually needs no additional configurable part in gateleen.
Not that for hooks, this requires that we can override the queue used for
the propagated request. This is something we have in the pipeline in our
project but have not yet created a gateleen issue...
Let's have a look together to coordinate this.

**Comment by mcweba** [comment]
As discussed with @lbovet we do not implement this functionality directly in gateleen. The requirements are very project specific and therefore it would not make much sense to implement this in gateleen.

Since the _HookHandler_ only requires the _RequestQueue_ interface, a project using gateleen is free to implement this interface how ever they want.
