### ISSUE TITLE
Directly enqueue to destination queue when x-queue is set

### ISSUE THREAD

**Issue by thwint** [swisspush/gateleen#186]
Currently when specifying a x-queue header in hook definition "staticHeaders", the default listener-hook prefixed is used for a very short time to deliver to the queue defined in x-queue.

We can optimize by directly enqeuing into the queue defined by x-queue and bypass the default listener one.

**Comment by mcweba** [comment]
Fixed in release [v1.1.22](https://github.com/swisspush/gateleen/releases/tag/v1.1.22)
