### ISSUE TITLE
Duplicated Cross-Origin headers 'Access-Control-Allow-*'

### ISSUE THREAD

**Issue by bertranoel** [swisspush/gateleen#192]
In some cases, when a request is made with the header 'Origin', the 'Allow-Control-Allow-*' are duplicated.
This only appears when the request has an 'expand' or 'delta' parameter set and the CORSHandler is activated.

Request :
`curl 'http://localhost:7012/server/v1/menus?expand=1' -H 'Origin: http://127.0.0.1:8888'`

Response headers :
`Access-Control-Allow-Credentials →true, true`
`Access-Control-Allow-Methods →GET, POST, OPTIONS, PUT, DELETE, GET, POST, OPTIONS, PUT, DELETE`
`Access-Control-Allow-Origin →http://127.0.0.1:8888, http://127.0.0.1:8888`

**Comment by lbovet** [comment]
Fixed with #193 
Many thanks!

**Comment by mcweba** [comment]
Reopened since causing errors

**Comment by oli-h** [comment]
can be closed - fixed with Gateleen 1.1.24
