### ISSUE TITLE
use different JSON schema/validation library

### ISSUE THREAD

**Issue by oli-h** [swisspush/gateleen#202]
gateleen-validation uses FGE library (https://github.com/java-json-tools/json-schema-validator).
But:
1. This library is no more maintained - last remarkable activity January 2014.
2. This library has weak performance
3. gateleen-validator requires to parse schema files over and over again. This results in even weaker performance

Proposal:
1. Get rid of FGE's library and use https://github.com/networknt/json-schema-validator. It performace 10x faster and is actively maintained. Additionally, the validation are more informative.
2. change gateleens validation pattern to separate schema loading (i.e. parsing JSON schema itself and creating a reusable Schema object) and validation process itself. This speeds up things as the schema parsing is quite expensive

**Comment by mcweba** [comment]
Released in [v1.1.40](https://github.com/swisspush/gateleen/releases/tag/v1.1.40)
