### ISSUE TITLE
Infinite hook expiration

### ISSUE THREAD

**Issue by hiddenalpha** [swisspush/gateleen#208]
(Moved from ISAGD-4839)

For permanent hooks, we currently need to set a very high value because the usual -1 value does not override the default expiration.

Just test the x-expire-after header before parsing it. If equals to -1, then do not set the hook expiration.

We are talking here about the expiration of the hook itself, not the propagated messages.

**Comment by hiddenalpha** [comment]
I'm working on it.

**Comment by mcweba** [comment]
merged with pull request #209
