### ISSUE TITLE
Remove unconditional "x-translate-status-4xx: 200" in HookHandler

### ISSUE THREAD

**Issue by oli-h** [swisspush/gateleen#211]
### Background:
- a queued message (https://github.com/swisspush/vertx-redisques) could be delivered multiple times if the http-request reaches the target server while the matching "200 OK" http-response gets lost. RedisQues repeats until it receives a successful delivery confirmation, i.e. a 2xx http status code
- now think we have a DELETE request in a queue and the destination is vertx-rest-storage (https://github.com/swisspush/vertx-rest-storage). If the first delivery attempt succeeds (i.e. vertx-rest-storage answerd "200 OK") but this positive response does not reach RedisQues, then RedisQues delivers the DELETE a seconds time. Now vertx-rest-storage answers "404 not found" as the resource is not (or better _no more_) present.
This results in a blocked queue, as the 'head' of the queue can never be delivered with any "2xx success"

- to avoid such blocking one could add Gateleen's translate header to the queued request - here a header which finally translates a "404" response code (or any 4xx) to a "200 OK" - so the second delivery of a DELETE to vertx-rest-storage finally succeeds.
- Gateleen's HookHandler adds such a translate-header unconditionally (see https://github.com/swisspush/gateleen/blob/v1.1.25/gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java#L730) to ensure stable dequeuing  - otherwise every (external) service which places hooks would be required to add this header to every hook by itself - or have a risk of blocked queues (as described)
- **Problem:** If the target of a queued message is not vertx-rest-storage but an external server then a "404" answer should not be assumed to be a "200 OK"
_Example 1: classic JavaEE servers typically answer 404 for application-context-URLs while the application (WAR/EAR) is undeployed or deployment/undeployment is in progess - or deployment failed for some reason_
_Example 2: When the target server is behind a proxy (HAProxy, Load-Balancer, ...) they also can answer "404" without even forwarding the request in certain operation situations._
_Example 3: Other 4xx requests like "400 Bad request" or "401 unauthorized" are also silently accepted (i.e. translated to "200 OK") - but someone better should solve the causing problem and the queue should retain its messages until the problem is solved_
In such cases a queued message gets lost due to the "x-translate-status-4xx: 200" header - it was never delivered to the target application.

### Solution:
- remove this unconditional "x-translate-status-4xx: 200" header from HookHandler
- use vertx-rest-storage v2.5.2 which has an option to be nice (i.e. 200 OK) to DELETE requests to non-existing resources (https://github.com/swisspush/vertx-rest-storage/pull/50)
- _Note: the main (if not the only) reason for the unconditional "x-translate-status-4xx: 200" was this "404" behavior of vertx-rest-storage. As this can now be re-configured there is no need any more for this translate header._
- _Note 2: A hook placing service still can add such a translate header if needed_

**Comment by mcweba** [comment]
fixed in [v1.1.26](https://github.com/swisspush/gateleen/releases/tag/v1.1.26)
