### ISSUE TITLE
Gateleen sends "transfer-encoding: chunked" when forwarding http-GET

### ISSUE THREAD

**Issue by oli-h** [swisspush/gateleen#218]
See https://github.com/swisspush/gateleen/blob/v1.1.27/gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java#L208: _setChunked(true) is called always and unconditional for all outgoing http-Requests_

This is a problem for e.g. http-GET, as some http-server interpret this as an attack (called 'smuggling' or 'splitting' which tries to desync headers from body).

E.g. Oracle's WebLogic always closes the connection for security reasons - also if we explicit say "Connection: keep-alive". Even when the only transferred chunk is the "final" chunk with zero length (meaning a zero-site body) this makes no difference, at least in the "WebLogic" case.

Gateleen should be smart to only set "Transfer-Encoding: chunked" if there really **is** a body

**Comment by mcweba** [comment]
Released with [v1.1.28](https://github.com/swisspush/gateleen/releases/tag/v1.1.28)
