### ISSUE TITLE
Gateleen does not act properly when upstream server closes TCP connection ungraceful

### ISSUE THREAD

**Issue by oli-h** [swisspush/gateleen#221]
Szenario:
- a backend http Server and Gateleen running as Http-Proxy for url /gateleen/xyz on Port 7012 (org.swisspush.gateleen.routing.Forwarder) to this server
- Backend server has some handler to respond to a http-Request with body (e.g. http-POST) immediate with "200 OK", _without consuming the complete request body_ (or no body byte at all)
- Now send a POST http://localhost:7012/gateleen/xyz  with a huge request body in small chunks
- Gateleen forwards this request to backend (with org.swisspush.gateleen.routing.Forwarder), streaming the incoming request body to the outgoing request body - a http proxy
- Assume, backend server return "200 OK" **without first waiting for the complete http request body** (http allows this - at least some server do this, e.g. Jetty)
- In other words: A "200 OK" response is returned to Gateleen while the incoming http-request body is still streaming.
- Gateleen forwards this "200 OK" towards the client - also while that request-body is still streaming.
- The streaming of the request body continues - neither the client nor Gateleen have a problem with the already transferred response
... but if the Backend server now has a problem (e.g. full buffers due to the incoming stream) **it could close the TCP connection to ensure its own stability** (TCP FIN or TCP RST)
- Gateleen detects this close in exception handler and answers "503 service unavailable" to the Client

This is problematic:
- We **already have and forwarded a "200 OK"** answer for this http cycle. Vert.x knows this, too, and thus seems to ignore this second "statusCode/Message" from Gateleen
- The TCP connection with the client is kept intact - nobody said 'close'
- The client waits and 'hangs' on this connection as it still wants to continue with the transfer of the request body
- Finally, this TCP connection (Client -> Gateleen) is stale, as a request is still in progress.
- And  Timeout in Gateleen also does not fire as we got a "200" response

**Comment by mcweba** [comment]
Fixed in release [v1.1.29](https://github.com/swisspush/gateleen/releases/tag/v1.1.29)
