### ISSUE TITLE
DeltaHandler crash when handling "?delta=..." and response from upstream is unexpected

### ISSUE THREAD

**Issue by oli-h** [swisspush/gateleen#240]
To reproduce:
- compile Gateleen
- start Gateleen's playground and upload "some demo stuff" as documented in Gateleen
- Open http://localhost:7012/playground/browser.html?delta=0 in a browser

Problem is [DeltaHandler.java line 255](https://github.com/swisspush/gateleen/blob/v1.1.33/gateleen-delta/src/main/java/org/swisspush/gateleen/delta/DeltaHandler.java#L255).
A `io.vertx.core.json.DecodeException` is raised as the response body is no valid JSON (it's HTML here).
[This Exception is not catched](https://github.com/swisspush/gateleen/blob/v1.1.33/gateleen-delta/src/main/java/org/swisspush/gateleen/delta/DeltaHandler.java#L292) in the handler - finally `response.end()` is never called. The HttpServerRequest is left in a non-ended state. TCP-Connection is lost.

Additional finding:
- Exception is not logged - this makes it hard to analyze.
- Reason for the non-logging: There is no exceptionHandler registered in `org.swisspush.gateleen.core.http.BufferBridge` for `org.swisspush.gateleen.core.http.LocalHttpServerResponse`. A `setExceptionHandler(Throwable::printStackTrace);` [in the constructor of LocalHttpServerResponse](https://github.com/swisspush/gateleen/blob/develop/gateleen-core/src/main/java/org/swisspush/gateleen/core/http/LocalHttpServerResponse.java#L131-L134) would help

**Comment by hiddenalpha** [comment]
Thanks to @oli-h for this famous description. With this, it is no problem to reproduce 👍. Same for _additional findings_ 👍.

I'm working on it.

**Comment by hiddenalpha** [comment]
What would a expected response in this case look like?
5xx? 4xx? 2xx? With upstream body? empty body?

**Comment by oli-h** [comment]
Would say:
- "502 bad gateway"
- Exception in "502" response-Body
- Eventually the upstream response, too (but next to the exception)

**Comment by mcweba** [comment]
Released in version [v1.1.35](https://github.com/swisspush/gateleen/releases/tag/v1.1.35)
