### ISSUE TITLE
Vulnerable warning: Jackson < 2.8.11.3 has security issues

### ISSUE THREAD

**Issue by oli-h** [swisspush/gateleen#261]
Jackson-Library has various security issues.
Need to patch to >=2.8.11.3. See https://github.com/swisspush/gateleen/network/alert/pom.xml/com.fasterxml.jackson.core:jackson-databind/open

**Comment by mcweba** [comment]
Released in [v1.1.40](https://github.com/swisspush/gateleen/releases/tag/v1.1.40)
