### ISSUE TITLE
mvn install fails on osx

### ISSUE THREAD

**Issue by krital** [swisspush/gateleen#276]
Hello,

I am trying to build on latest osx and mvn fails as follows:

[INFO] --- frontend-maven-plugin:0.0.22:install-node-and-npm (install node and npm profile trigged) @ gateleen-hook-js ---
[INFO] Installing node version v0.12.2
[INFO] Creating temporary directory /Users/krital/dev/yachtsense/gateleen/gateleen-1.1.44/gateleen-hook-js/node_tmp
[INFO] Downloading Node.js from http://artifactory.pnet.ch/artifactory/list/ext-binaries-local/node/v0.12.2/node-v0.12.2-darwin-x64.tar.gz to /Users/krital/dev/yachtsense/gateleen/gateleen-1.1.44/gateleen-hook-js/node_tmp/node.tar.gz
[INFO] No proxy was configured, downloading directly
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for gateleen 1.1.44:
[INFO]
[INFO] gateleen ........................................... SUCCESS [  0.741 s]
[INFO] gateleen-testhelper ................................ SUCCESS [  1.778 s]
[INFO] gateleen-core ...................................... SUCCESS [ 14.681 s]
[INFO] gateleen-validation ................................ SUCCESS [  3.778 s]
[INFO] gateleen-logging ................................... SUCCESS [  3.910 s]
[INFO] gateleen-monitoring ................................ SUCCESS [  3.887 s]
[INFO] gateleen-routing ................................... SUCCESS [  5.184 s]
[INFO] gateleen-packing ................................... SUCCESS [  0.144 s]
[INFO] gateleen-delta ..................................... SUCCESS [  1.469 s]
[INFO] gateleen-queue ..................................... SUCCESS [ 10.274 s]
[INFO] gateleen-delegate .................................. SUCCESS [  3.601 s]
[INFO] gateleen-expansion ................................. SUCCESS [  3.208 s]
[INFO] gateleen-merge ..................................... SUCCESS [  0.213 s]
[INFO] gateleen-user ...................................... SUCCESS [  3.102 s]
[INFO] gateleen-security .................................. SUCCESS [  4.357 s]
[INFO] gateleen-scheduler ................................. SUCCESS [  3.706 s]
[INFO] gateleen-hook ...................................... SUCCESS [ 14.066 s]
[INFO] gateleen-hook-js ................................... FAILURE [  0.615 s]
[INFO] gateleen-qos ....................................... SKIPPED
[INFO] gateleen-player .................................... SKIPPED
[INFO] gateleen-runconfig ................................. SKIPPED
[INFO] gateleen-playground ................................ SKIPPED
[INFO] gateleen-test ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:19 min
[INFO] Finished at: 2019-04-12T20:27:00+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:install-node-and-npm (install node and npm profile trigged) on project gateleen-hook-js: Could not download Node.js: Could not download http://artifactory.pnet.ch/artifactory/list/ext-binaries-local/node/v0.12.2/node-v0.12.2-darwin-x64.tar.gz: Unknown host artifactory.pnet.ch: nodename nor servname provided, or not known -> [Help 1]

Obviously the URL is invalid but as this is a maven (?) dependency I am unsure how to fix. Does it build for you somehow?

**Comment by hiddenalpha** [comment]
This is because we're using our own maven repository (private and with additional resources). Where we also provide node and npm for such builds.

To build it from outside our company, we have to override that setting somehow. I need to consult that code first so I can say more about how we could do that.

**Comment by hiddenalpha** [comment]
So. Took a look and found something:

It seems profile `publicRepos` matches your scenario. Therefore you could use:
```
mvn clean install -PpublicRepos
```
(Badly, I cannot try that here because I'm behind that corporation proxy)

**Comment by krital** [comment]
Thanks for this, seems to have resolved... Perhaps you should mention this in README.md ?

**Comment by hiddenalpha** [comment]
Yeah. Think hint in README would be good idea. Opened PR #277 for this.
