### ISSUE TITLE
Extend ACL with RoleMapping

### ISSUE THREAD

**Issue by Kusig** [swisspush/gateleen#285]
Often we have different ACL roles which have equal setup in Gateleen because those roles are used within backend applications only for further distinguishing roles.  In order to reduce configuration efforts and redundancy, Roles should be treated as well with Wildcard in addition in Gateleen Security module (acl):

Example:
z-paisa-fis-admin
z-paisa-fis-user
z-paisa-fis-manager

We would like to add only one ACL for  z-paisa-fis

Reference:  SDCISA-409

**Comment by mcweba** [comment]
Released in [v1.1.47](https://github.com/swisspush/gateleen/releases/tag/v1.1.47)
