### ISSUE TITLE
Improve RoleMapping with better role header forwarding control

### ISSUE THREAD

**Issue by Kusig** [swisspush/gateleen#312]
See as well issue #306 where a first improvement was implemented.
As the role mapping takes over control about the forwarded roles, it is necessary to get more control about what roles shall be forwarded and what roles not.
Sometimes, mapped roles shall only be used to be applied against the ACL or the role mapping itself but they shouldn't be distributed further in the request headers.

With this issue, the feature must be extended to define clearly, if the original role as well as the mapped role shall be forwarded or not.

**Comment by mcweba** [comment]
Released in [v1.1.54](https://github.com/swisspush/gateleen/releases/tag/v1.1.54)
