### ISSUE TITLE
Adapt the HookHandler to use staticHeaders

### ISSUE THREAD

**Issue by ljucam** [swisspush/gateleen#33]
We have to adapt the HookHandler to be able to define staticHeaders in a hook. 
`"hook": {
    "methods": [
      "PUT"
    ],
    "destination": "/test",
    "expireAfter": 86400,
    "staticHeaders" : {
      "x-queue-expire-after" : 20
    }
  }
`

Static headers overrides always currently set headers (as well as default headers).

**Comment by lbovet** [comment]
Also make sure that the "clear header" behaviour is also implemented as in https://github.com/swisspush/gateleen/pull/21
