### ISSUE TITLE
gateleen-kafka should use a property mapper upon initialization

### ISSUE THREAD

**Issue by geekrumper** [swisspush/gateleen#333]
"gateleen-kafka" seems to be one of the modules without a property mapper. This situation makes it a requirement to modifiy the configuration manually upon release. This can be avoided by passing properties to the KafkaHandler and replace wildcards with the given environment properties.

**Comment by mcweba** [comment]
Released in [v1.1.57](https://github.com/swisspush/gateleen/releases/tag/v1.1.57)
