### ISSUE TITLE
QueueProcessor: Introduce x-queue-retry-xxx request header

### ISSUE THREAD

**Issue by mcweba** [swisspush/gateleen#341]
The class [StatusCodeTranslator](https://github.com/swisspush/gateleen/blob/develop/gateleen-core/src/main/java/org/swisspush/gateleen/core/util/StatusCodeTranslator.java) provides a feature to translate response status codes based on the request header `x-translate-status-XXX`

Example:
```
"x-translate-status-400": "200"
```
Will translate all Requests responded with a **400 Bad Request** to a **200 OK**. However, this feature currently is only available during request forwarding (_Forwarder, StorageForwarder_, etc.)

It would be useful to also use this feature in the [QueueProcessor](https://github.com/swisspush/gateleen/blob/develop/gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueProcessor.java) class. The _QueueProcessor_ executes the request from the queueItem and has to wait for the response. When sucessful, the QueueItem gets removed from the queue, otherwise the queueItem resides in the queue until removed manually or get expired.

By adding the _translateStatus_ feature to the _QueueProcessor_, we could theoretically configure each queueItem with its own constraints. Typically this is not used, but this feature could **auto-remove** broken queueItems after the first try.

**The following real use case brought me to this issue**
We have queues which are triggered by listener-hooks. These queues are very time-critical. Whenever an invalid queueItem (from a queue with wrong body) appears, the result (from a delegate's jolt transformation) is **400 Bad Request**. This queueItem will never be fixed, but blockes the following queueItems. Defining an expiry value on the queueItem is not very practical since the queueItem could be valid but the destination is too slow.

**Comment by lbovet** [comment]
We could achieve the wanted behaviour with an additional routing rule on the way, right?
Is this proposal aiming at avoiding complexifying routing rules?

**Comment by mcweba** [comment]
Normally, we could achieve this behaviour with an additional routing rule. In the use case mentioned, it's not possible to solve this with an additional routing rule, because of the delegates. We cannot create a routing rule to catch the delegate execution (_/gateleen/server/admin/v1/delegates/my-fancy-delegate/execution_), because this request is handled by the _DelegateHandler_ and not the router (routing is always the last step, when no handler handled the request).

I think we also could avoid some complexitiy in routing rules with this feature.

**Comment by lbovet** [comment]
Is the concept of translation really what we need here? It looks more like introducing a retry strategy.
"x-queue-retry-400": 0 // no retry on 400 errors
In the current phase, we can support only 0, so that we don't need to maintain a counter. This can evolve later on if needed.
Default is "infinite".

**Comment by mcweba** [comment]
I like the idea of a _x-queue-retry-400_ (or with a regex pattern _x-queue-retry-4XX_) header. Limit the value to **0** would be an easy start for now. When (later) allowing more than 0 retries, we have to define who keeps track of the counting. Personally, I would suggest to let redisques be in charge of counting. It does not make sense for a _QueueProcessor_ to directly retry a _504 Gateway Timeout_ request 5 times. Redisques would try once, wait for the next run and then try again.

**Comment by lbovet** [comment]
Yes, multiple retries would make sense with a delay:
"x-queue-retry-delay-504": 5000 // Wait 5 seconds before retrying.
And yes, the retry count would be kept by redisques and provided to the QueueProcessor which makes the decision.
All this is hypothetical future stuff that we implement if it has value.

**Comment by mcweba** [comment]
We agree to let redisques take care ouf counting. What about the decisions. Let's take the _x-queue-retry-400_ with value **0** example. The QueueProcessor executes the request, the request failes and the _QueueProcessor_ resolves (instead of reject) the queueItem because of the zero remaining retries? Or does the _QueueProcessor_ not care at all and rejects the queueItem, when then redisques looks at the zero remainig retries (according to _x-queue-retry-400_) and pops the queueItem? I think this should be the responsibility of redisques and not the _QueueProcessor_

**Comment by lbovet** [comment]
I would not complexify the redisques API. If redisques must know the retry count, it must be passed in the queue item.
If we keep the decision of dropping the queueItem in the processor, we don't distribute this responsibility between redisques and the processor given that the decision to drop the queueItem could also be more complex than just the retry count (e.g take the expiration time in account). That's why I favor a design where redisques just adds a value "retries" in the message passed to the processor. This value  would be incremented each time redisques tries to processes the message. No decision logic, only counting.

**Comment by mcweba** [comment]
Ok, let's recap what's to implement in the first steps (this issue):
* Extend _QueueProcessor_ to resolve failing queueItems when a _x-queue-retry-XXX_ header with value **0** is present. Of course, the response code must match the _XXX_ in the header
* For now, redisques will remain unchanged. Later we can add a counting mechanism which reduces the remaining retries count on every rejected queueItem processing

**Comment by lbovet** [comment]
Yep!

**Comment by mcweba** [comment]
Released in [v1.1.60](https://github.com/swisspush/gateleen/releases/tag/v1.1.60)
