### ISSUE TITLE
Gateleen should not use deprecated "staticHeaders" syntax

### ISSUE THREAD

**Issue by hiddenalpha** [swisspush/gateleen#370]
Since [pull 201](https://github.com/swisspush/gateleen/pull/201) (2018-03-08) the "*staticHeaders*" syntax is deprecated (See [Release Notes of v1.1.25](https://github.com/swisspush/gateleen/releases/tag/v1.1.25) and [deprecated warning](https://github.com/swisspush/gateleen/blob/v1.1.25/gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java#L1317)).

**Actual behavior**:

We observed that this log is more and more flooding our logs. Now I found who is logging it. Interestingly it seems to be gateleen itself which is performing those deprecated requests. See for example [gateleen-hook.js line 107](https://github.com/swisspush/gateleen/blob/v1.1.68/gateleen-hook-js/src/main/webapp/app/js/gateleen-hook.js#L107).

**Expected behavior**:

Gateleen does NOT use deprecated headers syntax.

**Comment by mcweba** [comment]
Released in [v1.1.73](https://github.com/swisspush/gateleen/releases/tag/v1.1.73)
