### ISSUE TITLE
Gateleen Unexpectedly Closes Ongoing Streams

### ISSUE THREAD

**Issue by hiddenalpha** [swisspush/gateleen#386]
We discovered this issue a while now. But it took a lot of time to get to the root cause of the problems we had. And we never found if the problems origin lies in gateleen or somewhere in our code. For this reason we did not yet open this issue (until now).

Because it seems we found where our problems originated and tried to fix them. Therefore a PullRequest will follow shortly to address this issue :) (**Edit**: Here it is #387)

As it was hard to find the origin and it still is hard to explain what happens in words, I thought would be better to directly write a reproducer for it. It is available as the [RuleUpdateTest](https://github.com/hiddenalpha/gateleen/blob/a974ae53e0dbc3889af6f9ae5c1377b3365522ef/gateleen-test/src/test/java/org/swisspush/gateleen/routing/RuleUpdateTest.java) an shows how gateleen behaves in a way we do not expect.

**Comment by mcweba** [comment]
Does this behaviour only occur when the rules are changed while large requests are pending?

**Comment by hiddenalpha** [comment]
> Does this behaviour only occur when the rules are changed while large requests are pending?

Based on our observations I would say **yes**. There are even more conditions required:
- The rule change MUST be AFTER the long request started.
- The response body MUST be large enough to trigger backpressure through all the buffers back to the upstream server. Including all application/networkStack/etc buffers.
- The cleanup of the old connections MUST occur while the backpressure through to the upstream server is still in place.

**Comment by mcweba** [comment]
> > Does this behaviour only occur when the rules are changed while large requests are pending?
> 
> Based on our observations I would say **yes**. There are even more conditions required:
> 
> * The rule update MUST be AFTER the long request started.
> * The response body MUST be large enough to trigger backpressure through all the buffers back to the upstream server. Including all application/networkStack/etc buffers. (I guess a slow upstream could trigger that issue too but in  our case it is a slow downstream consumer).
> * The cleanup of the old connections MUST occur while the upstream server is still sending.

In this case I would prefer to make the usage of your decorations optional (i.e. Constructor flag in _Router_ class). Default behaviour should be without decorations. In NEMO we only change routing rules during planned changes on saturday evenings where we have almost no load.

**Comment by hiddenalpha** [comment]
> In this case I would prefer to make the usage of your decorations optional

Hmm. looks like a valid point. I'll take a look then.
