### ISSUE TITLE
Move integration tests to vertx-rest-storage

### ISSUE THREAD

**Issue by floriankammermann** [swisspush/gateleen#41]
There are integration tests in gateleen which are not testing gateleen functionality, but rest-storage functionality. These tests should be moved to https://github.com/swisspush/vertx-rest-storage:
- CrudTest
- PathLevelTest
- ExpandOffsetLimitTest
- StorageExpandTest

**Comment by mcweba** [comment]
I totally agree with this for the CrudTest and PathLevelTest. However, the "expand" tests also test the gateleen implmentations like _ExpansionHandler_. I would leave these tests in gateleen (or copy them to rest-storage).
