### ISSUE TITLE
Extend staticHeaders functionality

### ISSUE THREAD

**Issue by mcweba** [swisspush/gateleen#43]
With the current implemenation we can define static headers for routing rules like this:

``` json
{
    "/playground/tests/(.*)": {
        "path": "/playground/server/tests/$1",
        "storage": "main",
        "staticHeaders": {
            "X-Expire-After": "3600"
        }
    }
}
```

Defining a _X-Expire-After_ static header like in the example above will add this header to the request. However, an already added _X-Expire-After_ header will be **replaced**.

It would be useful to have a feature which allows to add a static headers **only when they are not already present**.

This could be accomplished by adding a **forced** flag. This flag would result in the following behaviour:

| Force flag | Behaviour |
| --- | :-- |
| true | Replaces (overrides) already defined header values with the staticHeader value |
| false | Does nothing when header value already exists, adds defined header value otherwise |
| not set | Replaces (overrides) already defined header values with the staticHeader value. This is used for backward compatibility, since headers are replaced in current implementation |

A possible staticHeader configuration could look like this:

``` json
{
    "/playground/tests/(.*)": {
        "path": "/playground/server/tests/$1",
        "storage": "main",
        "staticHeaders": {
            "X-Expire-After": { "value": "3600", "force": true }
        }
    }
}
```

**Comment by lbovet** [comment]
I like the backward compatible syntax.
Actually, there are several semantics to take in account:
- replace: write only if already exists
- complete: write only if not yet present
- default: write it in any case
Please also take care that staticHeaders stuff is also present in hooks.

**Comment by lbovet** [comment]
Actually, there is a problem with the union-like typing (either string or object). It prevents to generate code mapping for typed language (e.g. jackson in Java).
It would be better to have another object instead of "staticHeaders".
We could use "headers", since there is a possibility to have more features in the future that will be maybe more dynamic.

**Comment by oli-h** [comment]
We have an additional enhancement proposal concerning "staticHeaders": use variables to enable dynamic header values. Example:
```
"headers": {
  "x-queue": { "value": "thought-{x-deviceid}", condition: "..." }
}
```
The syntax {x-deviceid} will be replaced by dynamically from the (assume to exist) value of header x-deviceid.
It would be very fancy if we could also reference query parameters and URL parts as dynamic values.

And not to forget: We have those "staticHeaders" (or new just "headers") no only in static routing (https://github.com/swisspush/gateleen/blob/develop/gateleen-routing/README_routing.md) but also with Hooks (https://github.com/swisspush/gateleen/blob/develop/gateleen-hook/README_hook.md).
We should do it in both modules the same way
