### ISSUE TITLE
Make QueueClient injectable to allow custom queuing

### ISSUE THREAD

**Issue by lbovet** [swisspush/gateleen#44]
In QueueHandler and HookHandler, the QueueClient is instanciated with new.
I propose to make it overridable in order to allow custom implementation.
For example, on single-instance gateleen servers where we don't need persistence we can enqueue in memory, without redisques.

**Comment by mcweba** [comment]
what about DI? See [http://qrman.github.io/posts/2015/07/10/vertx3-guice/](http://qrman.github.io/posts/2015/07/10/vertx3-guice/)

**Comment by lbovet** [comment]
I would not make the project opinionated. I just want that handlers should be configurable at wish.
