### ISSUE TITLE
Implement a DelegateHandler as a new module

### ISSUE THREAD

**Issue by ljucam** [swisspush/gateleen#59]
Implement the delegate feature. With this mechanism we are able to replace a request by another. 
For example, we could make a GET that will be replaced by another one (or even a POST). This allows for creating cheap adapters.

Cookbook for the delegate: 
Name a delegate: 
`/gateleen/server/delegate/v1/delegates/<delegate>/`

Create a definition:
`/gateleen/server/delegate/v1/delegates/<delegate>/definition`

DelegateHandler automatically checks if the Pattern 
`/gateleen/server/delegate/v1/delegates/<delegate>/execution`
is called. 

Example: 
```
 // create a delegate
PUT /gateleen/server/delegate/v1/delegates/user-zip-copy/definition
{
    "methods": [ "PUT", "DELETE" ],
    "pattern": ".*/([^/]+.*)",
    "requests": [
        {
            "method": "POST",
            "url": "/gateleen/server/v1/copy",
            "payload": {
                "source": "/gateleen/$1?expand=100&zip=true",
                "destination": "/gateleen/zips/users/$1.zip"
            }
        }
        ]
    }
}

```

```
// create a hook triggering the delegate
PUT /gateleen/users/_hooks/listeners/user-zip-copy
{
    "destination": "/gateleen/server/delegate/v1/delegates/user-zip-copy/execution"
}
```

**Comment by lbovet** [comment]
As discussed, the delegate requests must be called synchronously. It is up to the delegate configuration to use a queue if async requests is wanted.
Also, the response of the last delegate request must be returned (status, headers, body).
In case of multiple delegate requests, if one fails, the following ones are not tried and the response of the  failing one is returned to the caller.
