### ISSUE TITLE
doneHandlers in Router are called every time the routing rules change

### ISSUE THREAD

**Issue by mcweba** [swisspush/gateleen#66]
<h3>Problem</h3>
In the Router class an ellipsis of doneHandlers can be passed.
```java
Handler<Void>... doneHandlers
```
The purpose of these doneHandlers is to get notified when the router is completely initialized.
Every time the routing rules are changed, the method
```java
void updateRouting(List<Rule> rules)
```
is called. This method includes the notification of the doneHandlers with the following loop
```java
for (Handler<Void> doneHandler : doneHandlers) {
	doneHandler.handle(null);
}
```
This behaviour is currently used in the HookHandler class. There, with every notification of the doneHandler the init method is called
```java
public void init() {
	registerListenerRegistrationHandler();
	registerRouteRegistrationHandler();

	loadStoredListeners();
	loadStoredRoutes();

	registerCleanupHandler();
}
```
leading to new consumers. The creation of new consumers in this case should be avoided.

<h3>Possible solution</h3>
To await the complete initialization of the Router class, a RouterFactory could be implemented which builds the Router and returns a Future holding the initialized Router. This could look something like this:

```java
public class RouterProvider {

	public Future<Router> buildRouter(Object param1, Object param2, Object param3) {
		Future<Router> future = Future.future();
		// instantiate the router and call future.complete() when ready
		return future;
	}	
}
```

The doneHandlers ellipsis parameter could then be removed from the constructors.

Please comment.

**Comment by ljucam** [comment]
After a short discussion with Laurent, we decided, that it’s currently not the time to change the API’s. Because of this, we will instead use a flag, which is set after the instantiation of the Router and checked before the execution of the handlers. 
Later on we may consider a change of the API.
