### ISSUE TITLE
Encoding problem listing collections?

### ISSUE THREAD

**Issue by cronosun** [swisspush/gateleen#90]
According to the spec (https://tools.ietf.org/html/rfc3986#page-13), those chars are allowed in url path sements:

```
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
path-abempty  = *( "/" segment )
segment       = *pchar
```

**Reproduction:**
Open Postman and PUT those resources to the gateleen storage (body does not matter) - note: only the last segment of the URL does matter:

- ``http://nemotest.pnet.ch:7012/nemo/server/tests/collection/1_hello-$&()*+,;=``
- ``http://nemotest.pnet.ch:7012/nemo/server/tests/collection/2_hello-$&()*+,;=``
- ``http://nemotest.pnet.ch:7012/nemo/server/tests/collection/3_hello-$&()*+,;=``
- ``http://nemotest.pnet.ch:7012/nemo/server/tests/collection/1_hello-:$&()*+,;=``
- ``http://nemotest.pnet.ch:7012/nemo/server/tests/collection/4_hello-:@$&()*+,;=``

Those path segments do not contain characters that need to be percent encoded (according to the spec).

Now do a GET using postman:

``http://nemotest.pnet.ch:7012/nemo/server/tests/collection/`` 

**Result**

```json
{
  "collection": [
    "1_hello-$&()*+,;=",
    "1_hello-§$&()*+,;=",
    "2_hello-$&()*+,;=",
    "3_hello-$&()*+,;=",
    "4_hello-§@$&()*+,;="
  ]
}
```

Note those two results - the character ``§`` - originally this was ``:``:
- ``1_hello-§$&()*+,;=``
- ``4_hello-§@$&()*+,;=`` 

GETing the resources (GET works with the URL used in PUT but **DOES NOT** work using the URL returned by the collection listing):

- 404: ``http://nemotest.pnet.ch:7012/nemo/server/tests/collection/4_hello-§@$&()*+,;=``
- 404: ``http://nemotest.pnet.ch:7012/nemo/server/tests/collection/1_hello-§$&()*+,;=``
- 200: ``http://nemotest.pnet.ch:7012/nemo/server/tests/collection/4_hello-:@$&()*+,;=``
- 200: ``http://nemotest.pnet.ch:7012/nemo/server/tests/collection/1_hello-:$&()*+,;=``

The problem can also be reproduced using the GUI:

![problem_grafisch](https://cloud.githubusercontent.com/assets/13786782/18464500/c3218106-7991-11e6-9623-76ba3b3774b9.png)

**Comment by cronosun** [comment]
Addition:
Similar problem also happens with expand=1.

**Reproduction**

1)
``PUT http://localhost:3332/gurgle_persistence/test/4_hello-:@$&()*+,;=``
Request-Body (Json)
```json
{
	"hello" : "world1"
}
```

2)
``PUT http://localhost:3332/gurgle_persistence/test/1_hello-:$&()*+,;=``
```json
{
	"hello" : "world2"
}
```

3)
``GET GET http://localhost:3332/gurgle_persistence/test?expand=1`` 
STATUS = 200
Content-Length →53
Content-Type →application/json; charset=utf-8
Body (**not valid json**):
```
{"test":["1_hello-§$&()*+,;=","4_hello-§@$&()*+,;="
```
Postman result:
![problem_storage_expand](https://cloud.githubusercontent.com/assets/13786782/18510143/c268a1d6-7a7c-11e6-8fb2-979b4a17ead5.png)

**Gegencheck: OK**
``PUT http://localhost:3332/gurgle_persistence/test2/hello1`` 
```json
{
	"hello" : "world1"
}
```

``PUT http://localhost:3332/gurgle_persistence/test2/hello2``
```json
{
	"hello" : "world2"
}
```

``GET http://localhost:3332/gurgle_persistence/test?expand=1`` 
Response
```json
{
  "test2": [
    "hello1",
    "hello2"
  ]
}
```

**Comment by floriankammermann** [comment]
This issue was moved to swisspush/vertx-rest-storage#28
